services:
  diagai-landing:
    build: .
    container_name: diagai-landing
    ports:
      - "80:80"
    volumes:
      - ./assets/videos:/usr/share/nginx/html/assets/videos
      - ./download:/usr/share/nginx/html/download
    restart: unless-stopped
