server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    include /etc/nginx/mime.types;
    types {
        application/vnd.android.package-archive apk;
    }
    default_type application/octet-stream;

    location / {
        try_files $uri $uri/ =404;
    }

    location /landing/ {
        alias /usr/share/nginx/html/;
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(mp4|jpg|jpeg|png|apk)$ {
        add_header Cache-Control "public, max-age=604800";
    }
}
